server:
  port: 8080

spring:
  datasource: # not used now
    url: jdbc:mysql://localhost:3306/publish_subscribe_system
    username: root
    password: #password
    driver-class-name: com.mysql.cj.jdbc.Driver
#  rabbitmq:
#    host: localhost # Kubernetes Service Name for RabbitMQ
#    port: 5672
#    username: guest
#    password: guest







